# Open-Meteo API with WxData

In this example, we will demonstrate using WxData with the Open-Meteo API by doing the following:

1) Downloading the latest GFS & ECMWF Solar Radiation Forecast Data

## Imports

In [1]:
from wxdata import open_meteo_api_solar_radiation

### Retrieve Solar Radiation Forecasts via Open-Meteo API

In [2]:
gfs = open_meteo_api_solar_radiation.solar_radiation_forecast(34.54, 
                                                             -115.34, 
                                                             model='ncep gfs global 0.11/0.25')

In [3]:
gfs

,time,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance,global_tilted_irradiance,terrestrial_radiation,shortwave_radiation_instant,direct_radiation_instant,diffuse_radiation_instant,direct_normal_irradiance_instant,global_tilted_irradiance_instant,terrestrial_radiation_instant
0,2026-08-04 00:00:00,599.0,531.0,68.0,869.2,599.0,811.6,513.4,455.1,58.3,744.9,513.4,695.6
1,2026-08-04 01:00:00,394.0,337.0,57.0,787.3,394.0,568.7,303.4,259.5,43.9,606.3,303.4,437.9
2,2026-08-04 02:00:00,180.0,140.0,40.0,615.5,180.0,302.2,98.7,76.7,21.9,337.4,98.7,165.6
3,2026-08-04 03:00:00,19.0,11.0,8.0,133.4,19.0,50.3,0.0,0.0,0.0,0.0,0.0,0.0
4,2026-08-04 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2026-08-04 05:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2026-08-04 06:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2026-08-04 07:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2026-08-04 08:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2026-08-04 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2026-08-04 10:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2026-08-04 11:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2026-08-04 12:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2026-08-04 13:00:00,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,7.1
14,2026-08-04 14:00:00,65.0,42.0,23.0,335.4,65.0,142.7,127.2,82.2,45.0,656.5,127.2,279.4
15,2026-08-04 15:00:00,263.0,213.0,50.0,682.6,263.0,414.6,347.5,281.4,66.1,901.8,347.5,547.8
16,2026-08-04 16:00:00,474.0,409.0,65.0,807.1,474.0,673.4,558.9,482.2,76.6,951.6,558.9,793.9
17,2026-08-04 17:00:00,667.0,593.0,74.0,874.2,667.0,901.4,740.8,658.6,82.2,970.9,740.8,1001.1
18,2026-08-04 18:00:00,824.0,745.0,79.0,914.1,824.0,1083.0,878.9,794.6,84.3,974.9,878.9,1155.2
19,2026-08-04 19:00:00,929.0,846.0,83.0,932.2,929.0,1206.0,959.5,873.8,85.7,962.8,959.5,1245.5
20,2026-08-04 20:00:00,977.0,893.0,84.0,940.5,977.0,1261.7,980.4,896.1,84.3,943.7,980.4,1266.1
21,2026-08-04 21:00:00,966.0,883.0,83.0,941.3,966.0,1246.6,941.8,860.9,80.9,917.7,941.8,1215.4
22,2026-08-04 22:00:00,892.0,812.0,80.0,929.0,892.0,1161.5,842.4,766.8,75.6,877.3,842.4,1096.9
23,2026-08-04 23:00:00,763.0,687.0,76.0,901.9,763.0,1012.3,692.4,623.5,69.0,818.5,692.4,918.6

In [4]:
ecmwf = open_meteo_api_solar_radiation.solar_radiation_forecast(34.54, 
                                                             -115.34, 
                                                             model='ecmwf ifs hres 9km')

In [5]:
ecmwf

,time,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance,global_tilted_irradiance,terrestrial_radiation,shortwave_radiation_instant,direct_radiation_instant,diffuse_radiation_instant,direct_normal_irradiance_instant,global_tilted_irradiance_instant,terrestrial_radiation_instant
0,2026-08-04 00:00:00,588.0,498.0,90.0,815.3,588.0,811.5,504.0,426.8,77.1,698.8,504.0,695.5
1,2026-08-04 01:00:00,383.0,307.0,76.0,717.2,383.0,568.7,295.0,236.5,58.5,552.4,295.0,438.0
2,2026-08-04 02:00:00,173.0,121.0,52.0,531.7,173.0,302.3,94.9,66.4,28.5,291.7,94.9,165.9
3,2026-08-04 03:00:00,21.0,10.0,11.0,121.2,21.0,50.5,0.0,0.0,0.0,0.0,0.0,0.0
4,2026-08-04 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2026-08-04 05:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2026-08-04 06:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2026-08-04 07:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2026-08-04 08:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2026-08-04 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2026-08-04 10:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2026-08-04 11:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2026-08-04 12:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2026-08-04 13:00:00,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,7.6
14,2026-08-04 14:00:00,67.0,41.0,26.0,327.1,67.0,143.1,130.9,80.1,50.8,639.3,130.9,279.7
15,2026-08-04 15:00:00,254.0,191.0,63.0,611.8,254.0,414.9,335.5,252.3,83.2,808.0,335.5,547.9
16,2026-08-04 16:00:00,463.0,380.0,83.0,749.8,463.0,673.5,545.8,448.0,97.8,883.9,545.8,793.9
17,2026-08-04 17:00:00,656.0,561.0,95.0,827.1,656.0,901.3,728.5,623.0,105.5,918.6,728.5,1001.0
18,2026-08-04 18:00:00,812.0,709.0,103.0,870.1,812.0,1082.8,866.0,756.2,109.9,928.0,866.0,1154.9
19,2026-08-04 19:00:00,919.0,811.0,108.0,893.9,919.0,1205.7,949.2,837.6,111.5,923.2,949.2,1245.2
20,2026-08-04 20:00:00,969.0,858.0,111.0,903.9,969.0,1261.4,972.3,861.0,111.4,907.0,972.3,1265.7
21,2026-08-04 21:00:00,956.0,846.0,110.0,902.1,956.0,1246.2,932.1,824.8,107.2,879.5,932.1,1215.1
22,2026-08-04 22:00:00,883.0,776.0,107.0,888.1,883.0,1161.2,833.9,732.9,101.1,838.7,833.9,1096.6
23,2026-08-04 23:00:00,753.0,653.0,100.0,857.5,753.0,1012.0,683.4,592.6,90.8,778.2,683.4,918.4